server:
  port: 2300

photon:
  ip: "localhost"
  port: 2322

map:
  location:
    autosearch:
      filtering:
        enable: true
        countries: PL,DE,FR
        cities: Gliwice, Opole, Sucha Bezkidzka
        photon:
          limit: 0
        api:
          limit: 8
      search:
        useBoundary: false
        W_boundary: 180
        S_boundary: 90
        E_boundary: 180
        N_boundary: 90
    reverseGeocode:
      filtering:
        enable: true

management:
  endpoints:
    web:
      exposure:
        include: info